### ISSUE TITLE
The following modules couldn't be hot updated: (Full reload needed)

### ISSUE THREAD

**Issue by 0x80** [gaearon/react-transform-hmr#42]
With some of my components I'm getting the following message all the time.

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
app.js:839 [HMR]  - ./~/css-loader?sourceMap&modules&localIdentName=[name]--[local]--[hash:base64:5]!./~/postcss-loader!./app/styles/Tag.css
```

Any idea why this might happen? Below is the source of my component and its stylesheet.

``` javascript
import { PropTypes } from 'react'
import cx from 'classnames'
import s from 'styles/Tag'


Tag.propTypes = {
  selected: PropTypes.bool.isRequired,
  label: PropTypes.string.isRequired,
  onClick: PropTypes.func.isRequired
}

export default function Tag({selected, label, onClick}) {

  const classes = cx(s.main, {
    [s.selected]: selected
  })

  return (
    <span className={classes} onClick={onClick}>{label}</span>
  )
}
```

``` css
@import 'variables/all';

.main {
  height: 1.5em;
  background-color: var(--color-white);

  line-height: 1;
  text-align: center;
  vertical-align: middle;
  padding: 0.2em;

  border: 1px solid var(--color-gray);

  &.selected {
    background-color: var(--color-gray);
    color: var(--color-white);
  }
}
```
